return {}
-- return {
--   {
--     "zbirenbaum/copilot.lua",
--     config = function()
--       require("copilot").setup({
--         suggestion = { enabled = false },
--         panel = { enabled = false },
--       })
--     end,
--     keys = {
--       {
--         "<leader>at",
--         function()
--           if require("copilot.client").is_disabled() then
--             require("copilot.command").enable()
--           else
--             require("copilot.command").disable()
--           end
--         end,
--         desc = "Toggle (Copilot)",
--       },
--     },
--   },
-- }
