return {
  -- {
  --   "neovim/nvim-lspconfig",
  --   opts = {
  --     servers = {
  --       pyright = {
  --         mason = false,
  --         autostart = false,
  --       },
  --     },
  --   },
  -- },
  -- {
  --   "folke/snacks.nvim",
  --   opts = {
  --     picker = {
  --       formatters = {
  --         file = {
  --           truncate = 90,
  --         },
  --       },
  --     },
  --   },
  -- },
}
